version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  groups:
    production-dependencies:
        dependency-type: "production"
    development-dependencies:
        dependency-type: "development"
    koa:
      patterns:
        - "koa*"
        - "@types/koa*"
 
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  reviewers:
  - berviantoleo
  assignees:
  - berviantoleo

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  reviewers:
  - berviantoleo
  assignees:
  - berviantoleo
